tutorial/WORKSPACE

See https://groups.google.com/d/msg/bazel-discuss/UIpdUTW47LQ/8vu4aA08BQAJ.

Update AppEngine rule version

---

cpp-tutorial/stage1/main/BUILD
cpp-tutorial/stage1/main/hello-world.cc
cpp-tutorial/stage2/main/BUILD
cpp-tutorial/stage2/main/hello-greet.cc
cpp-tutorial/stage2/main/hello-greet.h
cpp-tutorial/stage2/main/hello-world.cc
cpp-tutorial/stage3/lib/BUILD
cpp-tutorial/stage3/lib/hello-time.cc
cpp-tutorial/stage3/lib/hello-time.h
cpp-tutorial/stage3/main/BUILD
cpp-tutorial/stage3/main/hello-greet.cc
cpp-tutorial/stage3/main/hello-greet.h
cpp-tutorial/stage3/main/hello-world.cc
java-tutorial/BUILD
java-tutorial/src/main/java/com/example/Greeting.java
java-tutorial/src/main/java/com/example/ProjectRunner.java
java-tutorial/src/main/java/com/example/cmdline/BUILD
java-tutorial/src/main/java/com/example/cmdline/Runner.java
tutorial/WORKSPACE
tutorial/ios-app/BUILD

This adds the Java project required to complete the Java build tutorial.

Update sample projects for Bazel tutorials.

---

tutorial/ios-app/BUILD

Also ran buildifier on ios-app/BUILD.

Add visibility attribute to ios-app to allow building //:all to work.

---

java-tutorial/BUILD
tutorial/ios-app/BUILD

Reverts bazelbuild/examples#29

Revert "Update the Java example BUILD file to match the Java tutorial text."

---

rules/attributes/BUILD
rules/attributes/printer.bzl
rules/computed_dependencies/BUILD
rules/computed_dependencies/comments.sh
rules/computed_dependencies/hash.bzl
rules/computed_dependencies/hello.txt
rules/computed_dependencies/spaces.sh
rules/custom_outputs/BUILD
rules/custom_outputs/extension.bzl
rules/default_outputs/BUILD
rules/default_outputs/extension.bzl
rules/empty/BUILD
rules/empty/empty.bzl
rules/executable/BUILD
rules/executable/executable.bzl

- How to create an empty rule
- How to access rule attributes
- How to compute implicit dependencies based on the attributes
- How to use attr.output_list
- How to create an executable rule
- How to create a rule with a declared output

Add more examples from the cookbook.

---

cpp-tutorial/stage1/main/hello-world.cc

Add missing <string> include to hello-world.cc

---

cpp-tutorial/stage3/README.md

Update README.md package => target

---

.gitignore

as well as Maven target/ in preparation for upcoming mvn2bazel example

add Eclipse IDE files to .gitignore

---

rules/computed_dependencies/hash.bzl
rules/depsets/foo.bzl
rules/expand_template/hello.bzl
rules/mandatory_provider/sum.bzl
rules/optional_provider/sum.bzl
rules/runfiles/execute.bzl
rules/shell_command/size.bzl

All examples are now working with --all_incompatible_changes.

Remove deprecated features from examples

---

.bazelci/presubmit.yml
android/firebase-cloud-messaging/README.md
android/firebase-cloud-messaging/WORKSPACE
android/firebase-cloud-messaging/app/google-services.json
android/firebase-cloud-messaging/app/put_google-services.json_here

Use a fake google-services.json for CI to build.
cc @ahumesky

Fix FCM example on CI

---

android/firebase-cloud-messaging/WORKSPACE
android/firebase-cloud-messaging/app/BUILD

Migrate Android FCM example to use rules_jvm_external

---

rules/shell_command/BUILD
rules/shell_command/rules.bzl

Fixes https://github.com/bazelbuild/examples/issues/103

emit_size(): fix on macOS

---

.bazelci/presubmit.yml

To unblock https://github.com/bazelbuild/bazel/issues/6622

Exclude tests that doesn't work with --incompatible_windows_native_test_wrapper

---

.bazelci/presubmit.yml
java-tutorial/BUILD

The contents of the BUILD file was from a later stage in tutorial.

Fix the contents of BUILD for java-tutorial

---

android/firebase-cloud-messaging/WORKSPACE
android/firebase-cloud-messaging/app/BUILD
android/ndk/WORKSPACE
android/ndk/app/src/main/BUILD.bazel
cpp-tutorial/stage1/main/BUILD
cpp-tutorial/stage2/main/BUILD
cpp-tutorial/stage3/lib/BUILD
cpp-tutorial/stage3/main/BUILD
java-maven/BUILD
java-maven/WORKSPACE
java-tutorial/BUILD
java-tutorial/src/main/java/com/example/cmdline/BUILD
rules/WORKSPACE
rules/actions_run/BUILD
rules/aspect/BUILD
rules/depsets/BUILD
rules/expand_template/BUILD
rules/shell_command/BUILD
tutorial/WORKSPACE
tutorial/android/BUILD
tutorial/backend/BUILD
tutorial/ios-app/BUILD

This fixes future Bazel incompatibilities.
Updated WORKSPACE files manually.

Run `buildifier --lint=fix -r .`

---

android/firebase-cloud-messaging/WORKSPACE

Fixes https://github.com/bazelbuild/examples/issues/146

Ping Android SDK version to 28.0.2

---

CODEOWNERS
rules/starlark_configurations/README.md

add starlark_configurations dir and owners for it

---

make-variables/README.md
make-variables/testapp/BUILD
make-variables/testapp/app.cc
make-variables/testapp/defs.bzl

for https://github.com/bazelbuild/bazel/issues/11322
after this, we can update the BE to remove the long code blocks (or at least shorten them).

Add example on "Make" variables

---

rules/starlark_configurations/transition_on_native_flag/BUILD
rules/starlark_configurations/transition_on_native_flag/README.md
rules/starlark_configurations/transition_on_native_flag/defs.bzl

add transition on native flag example

---

rules/starlark_configurations/basic_build_setting/README.md
rules/starlark_configurations/transition_on_native_flag/README.md

Fixing some package paths and standardizing printout format

---

rules/WORKSPACE
rules/starlark_configurations/use_skylib_build_setting/BUILD
rules/starlark_configurations/use_skylib_build_setting/README.md
rules/starlark_configurations/use_skylib_build_setting/defs.bzl

add example of using a skylib build setting

---

rules/starlark_configurations/select_on_build_setting/BUILD
rules/starlark_configurations/select_on_build_setting/README.md
rules/starlark_configurations/select_on_build_setting/defs.bzl

Add example of build setting and select

---

rules/starlark_configurations/label_typed_build_setting/BUILD
rules/starlark_configurations/label_typed_build_setting/README.md
rules/starlark_configurations/label_typed_build_setting/defs.bzl

Add an example of using a label-typed build setting

---

.bazelci/presubmit.yml
rules/starlark_configurations/read_attr_in_transition/BUILD
rules/starlark_configurations/read_attr_in_transition/README.md
rules/starlark_configurations/read_attr_in_transition/defs.bzl

...including a note about the reading configured attributed in rule transitions nuance. 
Work towards #154

An example of reading settings/attributes in the transition

---

android/tutorial/README.md

Add the link to the tutorial with this way it is easier to find from the repository

Add link to the Bazel Android tutorial

---

configurations/WORKSPACE
rules/WORKSPACE

udate bazel_skylib to newest version. This pr closes https://github.com/bazelbuild/examples/issues/254

udate bazel_skylib

---

configurations/cc_binary_selectable_copts/custom_settings/BUILD

For https://github.com/bazelbuild/bazel/issues/12933.

Update config_setting visibility.

---

.gitignore
tutorial/.bazelrc
tutorial/WORKSPACE

This is required to build the ios-app tutorial

Add new iOS CC toolchain

---

tutorial/WORKSPACE
tutorial/ios-app/BUILD

This gets it off of a SHA based commit.

Upgrade rules_xcodeproj to 1.3.2

---

rules/generating_code/BUILD
rules/generating_code/README.md
rules/generating_code/c_maybe.cc
rules/generating_code/gen/BUILD
rules/generating_code/gen/enum_maker.bzl
rules/generating_code/gen/enum_maker.py
rules/generating_code/p_maybe.py
rules/generating_code/values.txt

This is a toy example that shows
- a rule that builds a binary that can generate some code from an input file
- using that rule to create python and C++ source files
- which are consumed by *_library rules
- and, finally, by *_binary rules.

Add an example of generating code and consuming it as a library.

---

bzlmod/02-override_bazel_module/MODULE.bazel

Fixes https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3269#018a3f77-e97f-489d-9ebf-53800dd3b3bc

bzlmod example: pin skylib version

---

java-tutorial/src/main/java/com/example/cmdline/BUILD

Runner depends on greeter and not on ProjectRunner in tutorial

---

.github/FUNDING.yml
CONTRIBUTING.md

Note, this change was indicated by product management team. Radhika asked that it be included in the scope of improvements to the long-term health of this repo.

feat: indicate that the examples may be community-funded.

---

frontend/MODULE.bazel
frontend/react/BUILD.bazel

fix(frontend/react): fix devserver start

---

.bazelci/android.yml
android/jetpack-compose/BUILD.bazel
android/ndk/BUILD.bazel
android/robolectric-testing/BUILD.bazel

Update Android examples to use new Android flags.

---

frontend/MODULE.bazel
frontend/lint.bzl

In particular, bazel-lib to 2.x

chore: update Aspect rules

---

frontend/MODULE.bazel

chore(deps): update frontend deps

---

cpp-tutorial/stage1/main/BUILD
cpp-tutorial/stage2/main/BUILD
cpp-tutorial/stage3/lib/BUILD
cpp-tutorial/stage3/main/BUILD

- Renamed WORKSPACE to MODULE.bazel
- removed `load`s from `rules_cc` in BUILD files, as that's still in flux.

Update C++ tutorial to use Bzlmod

---

android/ndk/README.md

Use `--android_platforms`, `--fat_apk_cpu` is deprecated

Update Android example readme

---

.bazelci/frontend.yml
.bazelci/tutorial-rust.yml

CI : https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4511#_
Bazel Examples (tutorial-rust (Rust Vendored Deps)  :  https://github.com/bazelbuild/examples/issues/553
Bazel Examples (frontend (basics_macos_lts), Bazel Examples (frontend (basics_linux_lts)  : https://github.com/bazelbuild/examples/issues/556#issuecomment-2699827825
CC Greenteam : @meteorcloudy

Skiping few tests which are failing in downstream

---

frontend/BUILD.bazel
frontend/MODULE.bazel
frontend/eslint.config.mjs
frontend/package.json
frontend/pnpm-lock.yaml
frontend/react/src/BUILD.bazel
frontend/tools/_run_under_cwd.sh
frontend/tools/lint/linters.bzl
frontend/tools/pnpm

Picked up https://github.com/bazelbuild/examples/pull/495 (I seem to have lost my write permissions on this repo)
FYI @fmeum

Renovate/aspect rules lint 1.x
