AUTHORS, CONTRIBUTORS, android-ndk/BUILD, android-ndk/BUILD.sysroot, android-ndk/CROSSTOOL, android-prebuilts/BUILD, android-prebuilts/gen-crosstool.py, android-prebuilts/get-toolchains.sh, protobuf-2.5.0/BUILD, protobuf-2.5.0/BUILD.src.google.protobuf, re2/BUILD, tutorial/android/src/main/java/com/google/bazel/example/android/activities/MainActivity.java, tutorial/appengine.BUILD, tutorial/backend/src/main/java/com/google/bazel/example/app/MyAppServlet.java, tutorial/ci/build.sh, tutorial/ios-app/UrlGet/AppDelegate.h, tutorial/ios-app/UrlGet/AppDelegate.m, tutorial/ios-app/UrlGet/UrlGet-Info.plist, tutorial/ios-app/UrlGet/UrlGetViewController.h, tutorial/ios-app/UrlGet/UrlGetViewController.m, tutorial/ios-app/UrlGet/main.m
The headers were modified with
`find . -type f -exec 'sed' '-Ei' 's|Copyright 201([45]) Google Inc|Copyright 201\1 The Bazel Authors|' '{}' ';'`
And manual edit for not Google owned copyright.
The list of authors were extracted from the git log.
=> Rationalize copyrights headers

tutorial/WORKSPACE, tutorial/backend/BUILD
This falls out from removing the @bazel_tools appengine rules.
=> Update tutorial to use rules_appengine repository

CONTRIBUTORS, java-maven/.gitignore, java-maven/BUILD, java-maven/README.md, java-maven/WORKSPACE, java-maven/src/main/java/com/example/myproject/App.java, java-maven/src/test/java/com/example/myproject/TestApp.java
Add an example Java project that uses Maven for getting dependencies.
https://github.com/bazelbuild/bazel/issues/1410
I'm in the midst of writing a Skylark rule for maven_jar and maven_server,
but while that is in progress, here's the example project that I'm testing with.
=> Implement an example maven project

tutorial/BUILD, tutorial/ci/setup_android_repositories.sh
The way the tutorial is build on ci was a bit off the way we build the other.
These two changes:
- create a `//:all` target to build that select automatically what to build using select.
- add a setup script for the android tooling so we can run that as a configure step.
=> Make the tutorial build more compatible with ci.bazel.io

tutorial/WORKSPACE
The online tutorial currently directs you to use tag 0.0.2, which is
obsolete and doesn't work any more. The master branch of the tutorial
was updated to use a specific commit, but the online tutorial wasn't.
This change updates the rule to use the latest tag (0.0.3). I'll also
fix up the online tutorial page, which is in a different repo.
=> Update AppEngine rule to use tag 0.0.3 rather than a specific commit

tutorial/ci/setup_android_repositories.sh
Stopgap (but not the proper fix) for https://github.com/bazelbuild/continuous-integration/issues/74.
=> Update default Android version to 24

tutorial/WORKSPACE
Needed as bazel at HEAD has some changes incompatible with the "0.0.1" version of apple rules, and it's breaking our CI.
=> sync ios tutorial apple rules repository to 07-19-17

tutorial/WORKSPACE
...so that it works after the removal of a few fields from `ctx.fragments.apple` .
=> update rules_apple so that it works with Bazel at HEAD

rules/computed_dependencies/hash.bzl, rules/custom_outputs/extension.bzl, rules/default_outputs/extension.bzl, rules/executable/executable.bzl, rules/expand_template/hello.bzl, rules/test_rule/line_length.bzl
Modify the examples to no longer use deprecated APIs. For example, instead of `ctx.action()`, the examples now use `ctx.actions.run()` and `ctx.actions.run_shell()`.
=> Remove usages of deprecated APIs

rules/depsets/foo.bzl
If we don't do this, transitive uses of foo_library three or more
layers deep fail to compile.
See also bazelbuild/rules_sass#33
=> Return DefaultInfo from _foo_library_impl()

tutorial/README.md
The formatting and linking to the Android and iOS sections of the tutorial README was slightly broken. This fixes up the issues.
=> Fix tutorial/README.md formatting and linking

android/ndk/WORKSPACE
Rule http_archive was recently deprecated.
**Error message:**
ERROR: error loading package '': Encountered error while reading extension file 'gmaven.bzl': no such package '@gmaven_rules//': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.`
**Bazel version:**
Bazel version:
INFO: Invocation ID: 80ba42f0-2fb4-4032-bc43-68dc0c55cce5
Build label: 0.20.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Nov 30 20:40:12 2018 (1543610412)
Build timestamp: 1543610412
Build timestamp as int: 1543610412
=> Android NDK: add drop-in replacement for http_archive

cpp-tutorial/stage3/lib/hello-time.h, cpp-tutorial/stage3/main/hello-greet.h
fixing the header guard names in the last cpp examples
=> fixing header guard name typo

tutorial/README.md, tutorial/WORKSPACE
Fix ios-app build with Bazel 0.20.0 and above due to the removal of
`native.http_archive rule`.
=> Fix ios-app build with Bazel 0.20.0 and above

.bazelci/presubmit.yml
The C++ library require an Android split transition that only happens at the android_binary.dep edge.
=> Don't build `//...` in the NDK examples.

.bazelci/presubmit.yml
The failures are from requesting non-existent test targets.
=> Fix Java tutorial on CI

.bazelci/presubmit.yml
//test_rule:80columns is the only test, excluding it will result no test being tested, Bazel returns non-zero.
=> Remove test_targets for rules-windows

rules/actions_run/BUILD, rules/actions_run/execute.bzl, rules/actions_run/merge.bat
//actions_run:merge will not hit merge.sh.
The proposed change updates the label so that it goes to //actions_run:merge.sh.
=> Point to executable

android/firebase-cloud-messaging/WORKSPACE
maven_jar is going away. See https://github.com/bazelbuild/bazel/issues/6799
=> Migrate maven_jar usage to rules_jvm_external

tutorial/WORKSPACE
Update `@io_bazel_rules_appengine` to use https
for Mavel URLs.
See https://github.com/bazelbuild/rules_appengine/commit/339f6aba67fcedb7268cf54d1163cf7704a277ca
Fixes https://github.com/bazelbuild/examples/issues/144
=> Update io_bazel_rules_appengine to fix https issue

rules/predeclared_outputs/hash.bzl
The error message in this code mixes `%` with format string substitution.
This leads to a mis-rendered error message that includes `%s` in the output.
=> Fix typo in "predeclared_outputs" example

android/firebase-cloud-messaging/WORKSPACE, rules/aspect/file_collector.bzl, rules/runfiles/BUILD, rules/runfiles/complex_tool.bzl, rules/runfiles/library.bzl, rules/runfiles/tool.bzl, tutorial/WORKSPACE
Run `buildifier --lint=fix -r .` manually.
Could buildifier be made part of CI of this repo?
If so we can follow this https://github.com/bazelbuild/buildtools/tree/master/buildifier#setup-and-usage-via-bazel 
Signed-off-by: Abhilash Gnan <abhilashgnan@gmail.com>
=> Run buildifier --lint=fix -r .

.bazelci/presubmit.yml, rules/starlark_configurations/multi_arch_binary/BUILD, rules/starlark_configurations/multi_arch_binary/README.md, rules/starlark_configurations/multi_arch_binary/defs.bzl
Final step for https://github.com/bazelbuild/bazel/issues/5575
Note - this logic isn't actually released in bazel yet but I think it's fine to document it prematurely.
=> add example for multi-arch binary

tutorial/WORKSPACE
rules_apple was broken by changes to Bazel at HEAD,
and updating rules_apple incorporates the fix.
=> Update rules_apple dependency to HEAD

tutorial/WORKSPACE
Old version is failing with bazel@HEAD, because of java_toolchain attribute javac and extclasspath.
=> Bump version of rules_appengine.

tutorial/WORKSPACE
Old version is failing on CI with Bazel@HEAD, because of
incompatibilities with the old java_toolchain definition.
=> Update version of rules_appengine

android/firebase-cloud-messaging/WORKSPACE
Remove `build_tools_version` and `api_level` to let `android_sdk_repository` automatically select the latest installed version.
One of the fixes for https://github.com/bazelbuild/bazel/issues/13409#issuecomment-845265150
=> Remove build_tools_version

rules/actions_run/execute.bzl
Update the docstring to refer to `merge_tool` attribute, not `_merge_tool` to match the implementation; remove the note about private attributes.
=> Update docstring in actions_run example.

cpp-tutorial/stage1/README.md
AFAIK there is no longer a need to use tripple slash in Windows, indeed you can have problems if you do:
https://github.com/bazelbuild/examples/issues/198
In case that I am wrong then we should change it to explain in which situation tripple slash might be needed.
=> Remove tripple slash on Windows

rules/actions_write/file.bzl, rules/aspect/file_collector.bzl, rules/computed_dependencies/hash.bzl, rules/depsets/foo.bzl, rules/expand_template/hello.bzl, rules/implicit_output/hash.bzl, rules/mandatory_provider/sum.bzl, rules/optional_provider/sum.bzl, rules/predeclared_outputs/hash.bzl
The `outputs` parameter of rule is deprecated. Hence don't use it in
examples where people are supposed to copy'n'paste from.
Documentation: https://docs.bazel.build/versions/main/skylark/rules.html#deprecated-predeclared-outputs
=> Migrate away from using the 'outputs' parameter

make-variables/README.md, make-variables/testapp/BUILD
Demonstrate every category in
https://docs.bazel.build/versions/main/be/make-variables.html#predefined_genrule_variables.
Except C++ and Java toolchain variables which are documented as "advanced" and
not intended for casual users.
For https://github.com/bazelbuild/bazel/issues/13886
=> Make make variable examples more comprehensive

.bazelci/presubmit.yml
This will skip testing those jobs with Bazel@HEAD in downstream pipeline.
We can re-enable them in downstream when https://github.com/bazelbuild/bazel/issues/14361 is fixed.
=> Set specific bazel version number for "Bazel Rules" job

rules/starlark_configurations/read_attr_in_transition/README.md
The line break between the `[configure attribute]` and the (link) itself broke markdown formatting.
=> Fix markdown link in README.txt

cpp-tutorial/stage2/main/hello-greet.h, third-party-dependencies/WORKSPACE
This PR pulls together a bunch of stale PRs that were typo or nit corrections.
- rewrite the description of the dependency loading idiom. Inspired by #236.
- Fix a header guard (from #122)
=> Rewrite WORKSPACE text for 3p example and other typos.

.bazelci/configurations.yml, .bazelci/presubmit.yml, .bazelci/rules.yml, configurations/attaching_transitions_to_rules/defs.bzl, configurations/basic_build_setting/README.md, configurations/cc_binary_selectable_copts/BUILD, configurations/cc_binary_selectable_copts/defs.bzl, configurations/label_typed_build_setting/README.md, configurations/label_typed_build_setting/defs.bzl, configurations/read_attr_in_transition/defs.bzl, configurations/select_on_build_setting/README.md, configurations/use_skylib_build_setting/BUILD, configurations/use_skylib_build_setting/README.md, configurations/use_skylib_build_setting/defs.bzl
https://github.com/bazelbuild/examples/commit/e5e9d051202565343708dcde2baa0010cb083731 refactored the WORKSPACES (so labels resolve differently).
Fixes https://github.com/bazelbuild/examples/issues/247
=> Add configuration tests back to CI

tutorial/WORKSPACE, tutorial/ios-app/BUILD
Recently we moved the ios-app tutorial into the rules_apple repo and iterated on it:
- https://github.com/bazelbuild/rules_apple/pull/1621
- https://github.com/bazelbuild/rules_apple/pull/1639
This PR pushes the latest updates to the example project stored in this repo. The next step would be to remove [the tutorial from the Bazel repo](https://github.com/bazelbuild/bazel/blob/master/site/en/start/ios-app.md) and link to the [document in rules_apple](https://github.com/bazelbuild/rules_apple/blob/master/doc/tutorials/ios-app.md).
=> Update ios-app example with latest additions

.bazelci/bzlmod.yml, bzlmod/01-depend_on_bazel_module/README.md, bzlmod/02-override_bazel_module/README.md, bzlmod/03-introduce_dependencies_with_module_extension/README.md, bzlmod/04-local_config_and_register_toolchains/README.md, bzlmod/05-integrate_third_party_package_manager/README.md, bzlmod/06-specify_dev_dependency/README.md, bzlmod/utils/librarian/librarian.bzl
- Renamed `--experimental_enable_bzlmod` to `--enable_bzlmod`
- Removed the need of `LIBRARIAN_BIN_PATH` env var
- Fix some markdown warnings
This will also fix [the downstream failure](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2728#01845f52-8d7b-42e4-8232-3589b9e8575d) which was caused by a wrong `LIBRARIAN_BIN_PATH` path.
=> Polish the Bzlmod examples

tutorial/WORKSPACE
Earlier version is broken with bazel@head due to deprecated targets being deleted in https://github.com/bazelbuild/bazel/commit/844b5d2dbc3ff1dda43d78b81a00c6323e4e8115
=> Update version of rules_appengine 

tutorial/WORKSPACE
This also changes the url to the new MobileNativeFoundation org.
=> Upgrade rules_xcodeproj to 1.3.3

README.md
- I tried to make the topic titles most likely to get search hits. So they might include extra words beyond the precise topic name.
- I excluded examples which were just confusing or wrong. TBH, some of the them are terrible. They are one line examples of a technique which should have been combined into a larger example that show two constrasting ways of doing something and their tradeoff.
=> Add a first-cut index to the README

android/ndk/app/src/main/BUILD.bazel
jni.h must be coming from cc_toolchain. Adding it just obscures an underlying problem, when NDK toolchain isn't selected.
=> Partial revert of "Fix missing jni.h when cc toolchain resolution is enabled"

.bazelci/tutorials.yml, tutorial/platform_mappings
Apple rules are supported using `platform_mappings`. Unfortunately we need a copy, and cannot refer directly to the one provider by rules_apple. By default Bazel is looking for the file in root directory (so it's enough to just add the file).
The change passes CI with C++ toolchain resolution enabled on mac.
=> Fix CI for C++ toolchain resolution

.pre-commit-config.yaml, bzlmod/03-introduce_dependencies_with_module_extension/deps.bzl, bzlmod/03-introduce_dependencies_with_module_extension/lib_a/deps.bzl, bzlmod/04-local_config_and_register_toolchains/local_config_sh.bzl, bzlmod/04-local_config_and_register_toolchains/sh_path.bzl, bzlmod/05-integrate_third_party_package_manager/lib_a/deps.bzl, bzlmod/05-integrate_third_party_package_manager/lib_b/deps.bzl, bzlmod/06-specify_dev_dependency/lib_a/deps.bzl, bzlmod/utils/librarian/librarian.bzl, configurations/attaching_transitions_to_rules/defs.bzl, configurations/basic_build_setting/defs.bzl, configurations/cc_binary_selectable_copts/defs.bzl, configurations/cc_test/defs.bzl, configurations/label_typed_build_setting/defs.bzl, configurations/multi_arch_binary/defs.bzl, configurations/read_attr_in_transition/defs.bzl, configurations/select_on_build_setting/defs.bzl, configurations/transition_on_native_flag/defs.bzl, configurations/use_skylib_build_setting/defs.bzl, flags-parsing-tutorial/build_defs.bzl, make-variables/testapp/defs.bzl, rules/depsets/foo.bzl, rules/executable/fortune.bzl, rules/implicit_output/hash.bzl, rules/predeclared_outputs/hash.bzl
Suppress existing warnings on files, since I don't know what the docstrings should have been.
=> chore: enable buildifier check for module docstrings

frontend/next.js/BUILD.bazel
This fixes an omission during migration to this repository.
Fixes #323
=> Fix path to next binary in Next.js example

.bazelci/misc.yml, java-maven/BUILD, java-maven/MODULE.bazel, java-maven/README.md, java-maven/container-structure-test.yaml
Examples of using Docker (or alternative container runtimes) are probably best layered next to existing applications, since it's not a language-specific ruleset.
=> chore: add container runtime to Java example 

frontend/pnpm-lock.yaml, frontend/react/package.json
This is a depracated version of `web-vitals`.
The v3 doesn't have the used functions anymore.
It would be better to port this code to use v3, but this at least allows users to bootstrap.
=> fix(frontend/react): pin `web-vitals` to 2.1.4

frontend/.bazelrc, frontend/BUILD.bazel, frontend/MODULE.bazel, frontend/README.md, frontend/lint.bzl, frontend/next.js/BUILD.bazel, frontend/next.js/package.json, frontend/next.js/pages/api/BUILD.bazel, frontend/package.json, frontend/pnpm-lock.yaml, frontend/react/BUILD.bazel, frontend/react/src/BUILD.bazel, frontend/react/src/index.tsx
Install a single eslint binary in the root of the pnpm workspace. Note, the version might not match what next.js or CRA would create in the subpackage.
Pass all eslint configs to the eslint aspect, so that it can visit any library target in the repo. ESLint should select the right configuration for each file.
In react, demonstrate using eslint as a test target rather than a build failure.
=> feat: demonstrate rules_lint for frontend monorepo

.bazelci/android.yml
Due to #400 
CC Greenteam @meteorcloudy
=> Disable android jetpack compose and robolectric testing in Bazel downstream

.bazelci/frontend.yml, frontend/MODULE.bazel
This is required by some newer dependencies such as next.js v14
=> chore(frontend): upgrade Node from v16 to v18

frontend/vue/BUILD.bazel
It already trivially works. It doesn't need to react to stdin.
fyi @igorminar
=> fix: vite devserver watch mode

.bazelci/tutorial-rust.yml
Reason : https://github.com/bazelbuild/examples/issues/540
CC @meteorcloudy
=> Skipping Testcases of Bazel examples in downstream.

rules/runfiles/complex_tool.bzl
Runfiles should not be merged as files, unless promoting data dependencies.
Fixes #556
=> Fix merging of runfiles library runfiles

rust-examples/01-hello-world/.bazelrc, rust-examples/02-hello-cross/.bazelrc, rust-examples/03-comp-opt/.bazelrc, rust-examples/04-ffi/.bazelrc, rust-examples/05-deps-cargo/.bazelrc, rust-examples/06-deps-direct/.bazelrc, rust-examples/07-deps-vendor/.bazelrc, rust-examples/08-grpc-client-server/.bazelrc, rust-examples/09-oci-container/.bazelrc
Fixes  https://github.com/bazelbuild/examples/issues/570  incompatible_merge_fixed_and_default_shell_env flag error in the CI https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4558#0195d0a3-12ed-486b-9936-22af4dbc34ac for all the Bazel Rust Examples.
CC Greenteam @meteorcloudy @fweikert
=> Fixes incompatible_merge_fixed_and_default_shell_env flag error

configurations/WORKSPACE, configurations/attaching_transitions_to_rules/defs.bzl, configurations/cc_binary_selectable_copts/defs.bzl, configurations/cc_test/README.md, configurations/cc_test/defs.bzl, configurations/multi_arch_binary/defs.bzl, configurations/read_attr_in_transition/defs.bzl, configurations/transition_on_native_flag/defs.bzl
No longer required since https://github.com/bazelbuild/bazel/commit/bb7fb2d32f055f2a70a5ab394cf5aef29bc74b2e (Bazel 7.0.0).
=> Remove outdated _allowlist_function_transition attribute
